Add Missing Type Annotations
adafruit/Adafruit_CircuitPython_MCP4728 pull request #14
Opened 2022-10-29 15:41 UTC by tcfranks

resolves #11 
submitted for review / comment

2022-10-30 17:45 UTC, tekktrik requested changes
Thanks!  Feedback below:

2022-10-30 17:45 UTC, tekktrik commented on adafruit_mcp4728.py
> +    def gain(self) -> Union[1, 2]:
I think you meant to use `Literal` instead of `Union`, which is why this is failing the CI.

2022-10-30 17:45 UTC, tekktrik commented on adafruit_mcp4728.py
> +    def _read_registers(self) -> Iterable[Tuple[int, int, int, int]]:
`Iterable` is correct, but we could be more specific here and use `List`:

```suggestion
    def _read_registers(self) -> List[Tuple[int, int, int, int]]:
```

2022-10-30 17:45 UTC, tekktrik commented on adafruit_mcp4728.py
> +    def _write_multi_eeprom(self, byte_list) -> None:
My guess is that, based on the implementation, `byte_list` is intended to be `List[int]`.

2022-10-30 17:45 UTC, tekktrik commented on adafruit_mcp4728.py
> +    def _set_value(self, channel: int) -> None:
Based on the use of `channel.channel_index`, `channel` should be `"Channel"`.

2022-10-30 17:45 UTC, tekktrik commented on adafruit_mcp4728.py
> +    def _chunk(big_list: bytearray, chunk_size: int) -> bytearray:
Oh, a generator!  We can type the use of `yield` using `typing.Generator`, and for less complex generators like this one, we can actually use `typing.Iterator`:

```suggestion
    def _chunk(big_list: bytearray, chunk_size: int) -> Iterator[bytearray]:
```

2022-10-30 17:45 UTC, tekktrik commented on adafruit_mcp4728.py
> +    def vref(self) -> Union[0, 1]:
Looks like this should also be `Literal` instead of `Union`

2022-10-31 16:40 UTC, tcfranks commented
resubmitted for review / comment

2022-11-21 17:33 UTC, FoamyGuy approved these changes
Looks good to me. Thank you @tcfranks!

2022-11-21 17:33 UTC, merged